import {
  CATALOG_CATEGORIES,
  CATALOG_ENTRIES,
  LAUNCH_POLICY,
  LIMITATIONS,
  MANUFACTURING_TECHNOLOGIES,
  MATERIAL_CAPABILITIES,
  VERIFIED_MODELS,
  capabilityVerdict,
  describeFact,
  manufacturingStatus,
  missingLaunchLimitations,
  processesAndMaterialsApproved,
  type CatalogEntry,
  type Fact,
  type FactState,
} from "@/content/catalog";
import { ROADMAP, capabilities, capabilityStatus, type CapabilityKind } from "@/content/catalog/capabilities";
import { LEDGER, decisionFor, isApproved, platformFor } from "@/content/catalog/decisions";
import { SERVICES } from "@/content/catalog/services";
import { assessLaunch } from "@/lib/catalog/launch";
import { formatINR } from "@/lib/money";

/**
 * The commercial catalog documents, rendered from the canonical modules.
 *
 *   MANUFACTURING_CAPABILITY.md   ← src/content/catalog/manufacturing.ts
 *   LAUNCH_CATALOG.md             ← src/content/catalog (entries, services)
 *                                   + lib/catalog/launch.ts (status, reasons)
 *
 * Generated, never hand-edited: `npm run content:docs` writes them and
 * `npm run content:docs -- --check` (also a unit test) fails when a file differs
 * from what the code says. A document that can drift from the data is a second
 * source of truth; one that cannot is a view.
 *
 * Deterministic: no clock, no environment. The same code renders the same bytes.
 */

const HEADER = (source: string) =>
  `<!-- GENERATED by \`npm run content:docs\` from ${source}. Do not edit by hand: change the source and regenerate. -->\n`;

const isVolume = (value: unknown): value is { x: number; y: number; z: number } =>
  typeof value === "object" && value !== null && ["x", "y", "z"].every((k) => typeof (value as Record<string, unknown>)[k] === "number");

const list = (value: unknown): string =>
  Array.isArray(value)
    ? value.join("; ")
    : isVolume(value)
      ? `${value.x} × ${value.y} × ${value.z} mm`
      : typeof value === "object" && value
        ? JSON.stringify(value)
        : String(value);

const MATERIAL_NAMES: Record<string, string> = { pla: "PLA", petg: "PETG", tpu: "TPU", abs: "ABS", resin: "Resin" };
const decided = (kind: "material" | "manufacturing-process", subjects: readonly string[], outcome: "APPROVED" | "NOT_APPROVED") =>
  subjects.filter((subject) => decisionFor(kind, subject)?.decision === outcome);

/** Escaping for table cells happens once, in `cell`. */
const fact = (value: Fact<unknown>): string => describeFact(value, list as never);

const factValueList = (value: Fact<unknown>): string[] =>
  value.state === "APPROVED" || value.state === "KNOWN" || value.state === "PROPOSED"
    ? (Array.isArray(value.value) ? value.value : [value.value]).map(String)
    : [];

const STATUS_TEXT = { AVAILABLE: "AVAILABLE", COMING_SOON: "COMING SOON", UNAVAILABLE: "UNAVAILABLE" } as const;

/** One kind's capabilities as "PLA — AVAILABLE; ABS — COMING SOON". */
const statusList = (kind: CapabilityKind, status?: keyof typeof STATUS_TEXT) =>
  capabilities(kind)
    .filter((row) => !status || row.status === status)
    .map((row) => (status ? row.label : `${row.label} — ${STATUS_TEXT[row.status]}`))
    .join(", ") || "none";

/** The three-state explanation, shared by all three documents' generated parts. */
const CAPABILITY_STATES = [
  "- **AVAILABLE** — approved by a Reality 3D business decision (a ledger record with a reference, an approver and a date). The only state that can be selected, quoted, carted, ordered, or used by a publishable product.",
  "- **COMING SOON** — planned, on the roadmap (`src/content/catalog/roadmap.json`), and **not approved**. Shown to customers as a future capability, muted and badged. The quote engine, cart, checkout and order creation refuse it; a product using it cannot be published or launch. A roadmap entry has no approver, no date and no specification — it is not an approval and cannot become one.",
  "- **UNAVAILABLE** — not approved and not planned. Not shown as an option.",
  "",
  "Capability status is about what Reality 3D can make. It is separate from Payload draft/published, from product approval, from technical validity and from price approval, which are questions about a product.",
];

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\n/g, " ");

const approvalLabel = (approval: { state: string; approval?: { reference: string; approvedOn: string } }) =>
  approval.state === "APPROVED" && approval.approval
    ? `APPROVED — ${approval.approval.reference} (${approval.approval.approvedOn})`
    : "NOT APPROVED";

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(cell).join(" | ")} |`),
  ].join("\n");
}

/** The state of a decision spread over several facts: approved only if all are. */
function aggregate(states: readonly FactState[]): FactState {
  if (states.length > 0 && states.every((state) => state === "APPROVED")) return "APPROVED";
  if (states.some((state) => state === "BLOCKED")) return "BLOCKED";
  if (states.some((state) => state === "PROPOSED" || state === "KNOWN")) return "PROPOSED";
  return "MISSING";
}

/* ------------------------------------------------------------------ *
 * MANUFACTURING_CAPABILITY.md
 * ------------------------------------------------------------------ */

export function renderManufacturingCapability(): string {
  const out: string[] = [
    HEADER("src/content/catalog/manufacturing.ts and the business decision ledger (src/content/catalog/decisions/business-decisions.json)"),
    "# Reality 3D — Manufacturing capability",
    "",
    "What Reality 3D manufactures, stated with the evidence for each part of it.",
    "",
    "- **KNOWN** — verified from the repository (a constant the software enforces, a rule in code), or a manufacturer specification Reality 3D supplied as the technical reference (for example printer nozzle sizes). A specification is not a production guarantee, and no tolerance is derived from it.",
    "- **PROPOSED** — entered or described, not signed off: PROPOSED — REQUIRES BUSINESS APPROVAL.",
    "- **MISSING** — nobody has supplied it. No value is shown, and none has been invented.",
    "- **APPROVED** — decided by Reality 3D, with a reference and a date.",
    "- **BLOCKED** — cannot be approved as things stand.",
    "",
    `**Overall: ${manufacturingStatus()}.** Processes and offered materials: ${processesAndMaterialsApproved() ? "APPROVED" : "NOT APPROVED"}. Launch-required limitations not yet approved: ${missingLaunchLimitations().join(", ") || "none"}. Manufacturing capability counts as approved for launch only when both hold.`,
    "",
    "Every approval on this page comes from a record in the business decision ledger (listed below). The application never infers an approval from a value being present in the configurator.",
    "",
    "## Capability status",
    "",
    ...CAPABILITY_STATES,
    "",
    table(
      ["Kind", "Available now", "Coming soon (not approved)", "Unavailable"],
      ([
        ["Manufacturing process", "technology"],
        ["Material", "material"],
        ["Finish", "finish"],
        ["Colour", "colour"],
      ] as const).map(([label, kind]) => [label, statusList(kind, "AVAILABLE"), statusList(kind, "COMING_SOON"), statusList(kind, "UNAVAILABLE")]),
    ),
    "",
    "**Coming soon is never counted as approved manufacturing capability.** The Overall line above, the launch gate and `content:verify` read approvals only. No machine, build volume, layer height, tolerance, lead time or date is recorded for any Coming Soon capability, and none may be added to the roadmap.",
    "",
    "## Technologies",
    "",
  ];

  for (const technology of MANUFACTURING_TECHNOLOGIES) {
    out.push(
      `### ${technology.value.toUpperCase()} — ${technology.name}`,
      "",
      table(
        ["Aspect", "State and value"],
        [
          ["Capability status", STATUS_TEXT[capabilityStatus("technology", technology.value)]],
          ["Status", fact(technology.status)],
          ["Printer", fact(technology.printer)],
          ["Machine / build envelope", fact(technology.buildEnvelopeMm)],
          ["Materials", fact(technology.materials)],
          ["Layer heights", fact(technology.layerHeights)],
          ["Nozzle / tooling", fact(technology.tooling)],
          ["Maximum hotend temperature", fact(technology.maxHotendTemperature)],
          ["Supported geometry", fact(technology.supportedGeometry)],
          ["Known limitations", fact(technology.knownLimitations)],
          ["Supported file types", fact(technology.fileTypes)],
          ["Typical lead time", fact(technology.leadTime)],
          ["Post-processing", fact(technology.postProcessing)],
          ["Inspection expectations", fact(technology.inspection)],
          ["Approval state", approvalLabel(technology.approval)],
        ],
      ),
      "",
    );
  }

  out.push(
    "## Material capability matrix",
    "",
    "Every material the configurator knows, in the state the ledger gives it. Only a material with an APPROVED decision on an APPROVED process is offered to customers — in the configurator, the storefront filters, the quote engine and the admin; the others are listed so their state is visible. An unsupported pairing (for example FDM layer heights on resin) is refused by validation and by the quote engine; it is not a row here.",
    "",
    table(
      ["Material", "Technology", "Capability status", "Status", "Colours", "Layer heights", "Finishes", "Approved"],
      MATERIAL_CAPABILITIES.map((capability) => [
        capability.name,
        capability.technology.toUpperCase(),
        STATUS_TEXT[capabilityStatus("material", capability.material)],
        fact(capability.status),
        fact(capability.colours),
        fact(capability.layerHeights),
        fact(capability.finishes),
        approvalLabel(capability.approval),
      ]),
    ),
    "",
    "## Manufacturing limitations",
    "",
    "Limitations that affect what a customer can order. No number appears unless it is enforced by the software (KNOWN) or approved.",
    "",
    table(
      ["Topic", "Policy", "Required before launch"],
      LIMITATIONS.map((limitation) => [limitation.topic, fact(limitation.policy), limitation.requiredForLaunch ? "Yes" : "No"]),
    ),
    "",
    "## Required before manufacturing sign-off",
    "",
    "Values that must come from Reality 3D manufacturing validation. None is derived from the printer specification, and none has been invented.",
    "",
    ...missingLaunchLimitations().map((topic) => `- **${topic}** — MISSING — REQUIRES Reality 3D MANUFACTURING VALIDATION (blocks launch).`),
    ...LIMITATIONS.filter((l) => !l.requiredForLaunch && l.policy.state === "MISSING").map((l) => `- ${l.topic} — MISSING (does not block the launch gate).`),
    "- Typical production lead time — MISSING.",
    "- Post-processing finishes other than Standard (Smoothed, Matte) — no decision; not offered.",
    "",
    "## Business decision ledger",
    "",
    "Append-only. A changed decision is a new record with a later date; the latest valid record for a kind and subject is in effect. Records that are malformed or conflict on the same date are not applied.",
    "",
    table(
      ["Id", "Kind", "Subject", "Decision", "Reference", "Approved by", "Approved on", "In effect"],
      LEDGER.accepted.map((record) => [
        record.id,
        record.kind,
        record.subject,
        record.decision,
        record.approval.reference,
        record.approval.approvedBy,
        record.approval.approvedOn,
        decisionFor(record.kind, record.subject)?.id === record.id ? "Yes" : "Superseded",
      ]),
    ),
    "",
    ...(LEDGER.issues.length
      ? ["**Not applied:**", "", ...LEDGER.issues.map((issue) => `- ${issue.recordId}: ${issue.message}`), ""]
      : []),
    "## Roadmap",
    "",
    "Presentation only. Each entry makes a capability visible as COMING SOON; none approves anything.",
    "",
    table(
      ["Kind", "Capability", "Status now", "Roadmap reference"],
      ROADMAP.entries.map((entry) => [
        entry.kind,
        capabilities(entry.kind).find((row) => row.value === entry.value)?.label ?? entry.value,
        STATUS_TEXT[capabilityStatus(entry.kind, entry.value)],
        entry.reference,
      ]),
    ),
    "",
    ...(ROADMAP.issues.length ? ["**Invalid roadmap entries (not shown):**", "", ...ROADMAP.issues.map((issue) => `- ${issue}`), ""] : []),
    "## How a decision becomes approved capability",
    "",
    "1. Write the decision as records in a JSON file: `{ \"schemaVersion\": 1, \"decisions\": [ … ] }`. Each record states its kind, subject, APPROVED or NOT_APPROVED, any values (a policy, a build volume, colours), and `{ reference, approvedBy, approvedOn }`.",
    "2. `npm run content:decisions -- --input <file>` — a dry run: every record is reported as accepted, duplicate or rejected, with reasons and the effect on the decision in force. Nothing is written.",
    "3. `npm run content:decisions -- --input <file> --apply` — appends the batch, only if no record is rejected. Re-applying the same file changes nothing.",
    "4. `npm run content:docs`, `npm test`, `npm run content:verify`, and a build: the storefront, configurator and quote engine read the ledger at build time.",
    "",
    "To move a capability from COMING SOON to AVAILABLE, record an APPROVED ledger decision for it (for a finish, kind `finish`), with any values it needs — for a new process, its machine and build volume; for a material, its colours. Editing the roadmap never does this. To show a planned capability as COMING SOON, add an entry to `roadmap.json` with a reference only.",
    "",
  );

  return out.join("\n");
}

/* ------------------------------------------------------------------ *
 * LAUNCH_CATALOG.md
 * ------------------------------------------------------------------ */

function productSection(entry: CatalogEntry): string[] {
  const { product, commercial } = entry;
  const launch = assessLaunch(entry, product, { now: new Date("2026-09-13T00:00:00.000Z") });
  const capability = capabilityVerdict(product.material, product.technology);
  const model = VERIFIED_MODELS.find((asset) => asset.url === product.model?.url);
  const dimensions = (product.specifications ?? [])
    .filter((row) => !/technology|layer height/i.test(row.label))
    .map((row) => `${row.label} ${row.value}`)
    .join("; ");

  const category = CATALOG_CATEGORIES.find((node) => node.value === product.browseCategory);
  const leaf = category?.children?.find((node) => node.value === product.category);

  const rows: string[][] = [
    ["Product ID", `KNOWN — ${product.id}`],
    ["Product name", `PROPOSED — ${product.name}`],
    ["SKU", fact(commercial.sku)],
    ["Slug", `KNOWN — ${product.slug}`],
    ["Category", `PROPOSED — ${category?.label ?? product.browseCategory} › ${leaf?.label ?? product.category}`],
    ["Product class", fact(commercial.productClass)],
    ["Customer", fact(commercial.customer)],
    ["Use case", fact(commercial.useCase)],
    ["Applications", `PROPOSED — ${(product.applications ?? []).join(", ") || "none"}`],
    ["Material", capability.approved ? `APPROVED — ${product.material.toUpperCase()} (business decision ledger)` : `NOT APPROVED — ${capability.reasons.join("; ")}`],
    ["Technology", isApproved("manufacturing-process", product.technology) ? `APPROVED — ${product.technology.toUpperCase()} (business decision ledger)` : `NOT APPROVED — ${product.technology.toUpperCase()}`],
    ["Colours", product.colors?.length ? `PROPOSED — ${product.colors.join(", ")} (within the approved colours; not approved for this product)` : "MISSING"],
    ["Dimensions", dimensions ? `KNOWN — ${dimensions} (measured from the model file)` : "MISSING — no dimensions recorded"],
    ["Weight", fact(commercial.weightGrams)],
    ["Manufacturing limitations", product.description ? `KNOWN — stated from the model: ${product.description}` : "MISSING"],
    ["3D model", model ? `KNOWN — ${model.url} (${model.format.toUpperCase()}, ${model.partCount} part${model.partCount === 1 ? "" : "s"}, parsed and measured)` : "MISSING"],
    ["Image", product.image ? (product.image.approval ? `APPROVED — ${product.image.src} (${product.image.approval.reference})` : `NOT APPROVED — ${product.image.src}`) : "MISSING — NO_IMAGE_YET"],
    ["Visual required", fact(commercial.visual.required)],
    ["Render specification", fact(commercial.visual.renderSpecification)],
    ["Pricing model", fact(commercial.pricingModel)],
    [
      "Price",
      product.priceStatus === "approved"
        ? `APPROVED — ${formatINR(product.price)}`
        : product.priceStatus === "quote-only"
          ? "QUOTE ONLY"
          : `PROVISIONAL — ${formatINR(product.price)}. ${entry.priceBasis} Not a commercial price.`,
    ],
    ["Price approval", entry.priceApprovals?.length ? entry.priceApprovals.map((r) => `${formatINR(r.amount)} from ${r.effectiveFrom} (${r.reference}, ${r.approvedBy})`).join("; ") : "NOT APPROVED — no price approval record"],
    ["Commercial copy", fact(commercial.copy)],
    ["Homepage feature", fact(commercial.featured)],
    ["Technical approval", launch.technical.status === "PASS" ? "PASS — validateProduct and validateCatalog" : `BLOCKING — ${launch.technical.reasons.join("; ")}`],
    ["Business approval", product.approvalStatus === "approved" && entry.approval ? `APPROVED — ${entry.approval.reference} (${entry.approval.approvedOn}, ${entry.approval.approvedBy})` : `NOT APPROVED — status ${product.approvalStatus}`],
    ["Launch status", launch.launch.ready ? "READY" : "NOT READY"],
  ];

  return [
    `### ${product.id} — ${product.name}`,
    "",
    table(["Field", "State and value"], rows),
    "",
    "**Why it cannot launch:**",
    "",
    ...(launch.launch.reasons.length ? launch.launch.reasons.map((reason) => `- ${reason}`) : ["- Nothing: launch-ready."]),
    ...(entry.contentGaps.length ? ["", "**Recorded gaps:**", "", ...entry.contentGaps.map((gap) => `- ${gap}`)] : []),
    "",
  ];
}

export function renderLaunchCatalog(): string {
  const assessments = CATALOG_ENTRIES.map((entry) => assessLaunch(entry, entry.product, { now: new Date("2026-09-13T00:00:00.000Z") }));
  const ready = assessments.filter((assessment) => assessment.launch.ready).length;
  const approved = CATALOG_ENTRIES.filter((entry) => entry.product.approvalStatus === "approved").length;
  const blocking = assessments.filter((assessment) => assessment.technical.status === "BLOCKING").length;
  const target = LAUNCH_POLICY.minimumApprovedProducts;

  const states = <T>(pick: (entry: CatalogEntry) => Fact<T>) => CATALOG_ENTRIES.map((entry) => pick(entry).state);

  const matrix: string[][] = [
    ["Manufacturing processes", [`APPROVED — ${decided("manufacturing-process", ["fdm", "sla"], "APPROVED").map((v) => v.toUpperCase()).join(", ") || "none"}`, `NOT APPROVED — ${decided("manufacturing-process", ["fdm", "sla"], "NOT_APPROVED").map((v) => v.toUpperCase()).join(", ") || "none"}`].join("; "), "Production / manufacturing lead", "Yes", "Yes"],
    ["Materials offered", [`APPROVED — ${decided("material", Object.keys(MATERIAL_NAMES), "APPROVED").map((v) => MATERIAL_NAMES[v]).join(", ") || "none"}`, `NOT APPROVED — ${decided("material", Object.keys(MATERIAL_NAMES), "NOT_APPROVED").map((v) => MATERIAL_NAMES[v]).join(", ") || "none"}`].join("; "), "Production / manufacturing lead", "Yes", "Yes"],
    ["Colours per material", aggregate(MATERIAL_CAPABILITIES.filter((m) => m.approval.state === "APPROVED").map((m) => m.colours.state)) === "APPROVED" ? `APPROVED — ${[...new Set(MATERIAL_CAPABILITIES.filter((m) => m.approval.state === "APPROVED").flatMap((m) => factValueList(m.colours)))].join(", ")}` : "MISSING", "Production / manufacturing lead", "Yes", "Yes"],
    ["FDM layer heights", aggregate(MANUFACTURING_TECHNOLOGIES.filter((t) => t.value === "fdm").map((t) => t.layerHeights.state)), "Production / manufacturing lead", "Yes", "Yes"],
    ["SLA layer heights", isApproved("manufacturing-process", "sla") ? aggregate(MANUFACTURING_TECHNOLOGIES.filter((t) => t.value === "sla").map((t) => t.layerHeights.state)) : "NOT APPLICABLE — SLA is not approved", "Production / manufacturing lead", "No", "No"],
    ["Printer and build envelope", platformFor("fdm") ? `APPROVED — ${platformFor("fdm")!.printer}, ${list(platformFor("fdm")!.buildVolumeMm)}` : "MISSING", "Production / manufacturing lead", "Yes", "Yes"],
    ["Launch-required limitations", missingLaunchLimitations().length ? `MISSING — ${missingLaunchLimitations().join(", ")}` : "APPROVED", "Production / manufacturing lead", "Yes", "Yes"],
    ["Production tolerance and inspection criteria", aggregate(LIMITATIONS.filter((l) => l.topic === "Production tolerance" || l.topic === "Inspection criteria").map((l) => l.policy.state)), "Production / manufacturing lead", "Yes", "No — not enforced by the gate"],
    ["Production lead time", aggregate(MANUFACTURING_TECHNOLOGIES.filter((t) => t.value === "fdm").map((t) => t.leadTime.state)), "Operations", "Yes", "No — not enforced by the gate"],
    ["Finishes beyond Standard (Smoothed, Matte)", `COMING SOON — ${statusList("finish", "COMING_SOON")}: no approval decision; not offered, quoted or orderable`, "Production / manufacturing lead", "No", "No"],
    ["Roadmap capabilities (Coming soon)", `COMING SOON — ${[statusList("technology", "COMING_SOON"), statusList("material", "COMING_SOON"), statusList("finish", "COMING_SOON")].join("; ")}. Planned, not approved; refused by quote, cart and checkout`, "Business owner / manufacturing lead", "No", "No — never counted as capability"],
    ["Catalog strategy", isApproved("catalog-policy", "catalog-strategy") ? "APPROVED — administrator-managed catalog" : "MISSING", "Business owner", "Yes", "No"],
    ["Best-seller claims", isApproved("catalog-policy", "sales-claims") ? "APPROVED — none without sales data; Recommended / Featured are admin-selected" : "MISSING", "Business owner", "Yes", "No"],
    ["Launch target", LAUNCH_POLICY.approved ? `APPROVED — ${target}` : `PROPOSED — ${target}, no launch-target decision`, "Business owner", "Yes", "Yes"],
    [`Product list (target ${target})`, `${CATALOG_ENTRIES.length === 0 ? "MISSING" : "PROPOSED"} — ${CATALOG_ENTRIES.length} defined`, "Business owner", "Yes", "Yes"],
    ["SKUs", aggregate(states((e) => e.commercial.sku)), "Business owner", "Yes", "Yes"],
    ["Product classes and pricing models", aggregate([...states((e) => e.commercial.productClass), ...states((e) => e.commercial.pricingModel)]), "Business owner", "Yes", "Yes"],
    ["Target customers and use cases", aggregate([...states((e) => e.commercial.customer), ...states((e) => e.commercial.useCase)]), "Business owner / marketing", "Yes", "Yes"],
    ["Product prices", CATALOG_ENTRIES.every((e) => e.product.priceStatus === "approved") ? "APPROVED" : "MISSING — provisional engine output only", "Business owner / finance", "Yes", "Yes"],
    ["Custom-print pricing rules (demo-2026-01)", "MISSING — rules are marked provisional", "Business owner / finance", "Yes", "Stage 20"],
    ["Product imagery", CATALOG_ENTRIES.every((e) => e.product.image?.approval) ? "APPROVED" : `MISSING — ${CATALOG_ENTRIES.filter((e) => e.product.image?.approval).length}/${CATALOG_ENTRIES.length} with an approved photo or render`, "Content / design", "Yes", "Yes"],
    ["Visual requirement per product", aggregate(states((e) => e.commercial.visual.required)), "Content / design", "Yes", "Yes"],
    ["Product copy sign-off", aggregate(states((e) => e.commercial.copy)), "Business owner", "Yes", "Yes"],
    ["Product approval (per product)", approved === CATALOG_ENTRIES.length && approved > 0 ? "APPROVED" : `MISSING — ${approved}/${CATALOG_ENTRIES.length} approved`, "Business owner", "Yes", "Yes"],
    ["Homepage featured products", aggregate(states((e) => e.commercial.featured)), "Business owner / marketing", "No", "No"],
    ["Additional products (admin-managed)", "MISSING — none supplied here; content:verify reports products entered in the CMS", "Business owner", "Yes", "Yes"],
    ["Planetary gear set without a ring gear", "MISSING — sell as is, or commission a ring-gear model", "Business owner", "For p-102", "For p-102"],
    ["CMS media storage adapter", "MISSING — images can be committed under public/catalog/ meanwhile", "Engineering decision", "No", "No"],
    ["Separate reviewer and approver roles in the CMS", "MISSING — one operator role exists", "Business owner", "No", "No"],
  ];

  const out: string[] = [
    HEADER("src/content/catalog (entries, services, manufacturing) and lib/catalog/launch.ts"),
    "# Reality 3D — Launch catalog",
    "",
    "The intended commercial catalog, product by product, with every input in the state it is actually in.",
    "",
    "The catalog is administrator-managed (Stage 19.8). This document lists the repository seed products (p-101 to p-103), which remain provisional until individually approved. Products created in the Payload admin are the business's own records: they are assessed in the admin's Launch tab and by `npm run content:verify`, not listed here.",
    "",
    `**ENGINEERING COMPLETE ≠ BUSINESS APPROVED ≠ LAUNCH READY.** Technically valid: ${CATALOG_ENTRIES.length - blocking}/${CATALOG_ENTRIES.length}. Business-approved: ${approved}/${CATALOG_ENTRIES.length}. Launch-ready: ${ready}/${CATALOG_ENTRIES.length}. CMS parity is a property of a database and is reported by \`npm run content:verify\`, not here.`,
    "",
    "## Catalog size",
    "",
    table(
      ["Launch target", "Defined", "Approved", "Launch-ready", "Technically blocking", "Gap"],
      [[String(target), String(CATALOG_ENTRIES.length), String(approved), String(ready), String(blocking), String(Math.max(0, target - ready))]],
    ),
    "",
    `The target comes from the launch policy (${LAUNCH_POLICY.reference.replace(/.$/, "")}). No product has been invented to approach it; products are added in the admin only when a business decision exists. Launching with fewer products is possible only by recording an explicit launch-target decision.`,
    "",
    "## Business input matrix",
    "",
    "Roles, not people: the ledger names the approver of each decision; no owner is otherwise named in the repository.",
    "",
    table(["Decision", "Current state", "Owner", "Required", "Blocking launch"], matrix),
    "",
    "## Products",
    "",
    ...CATALOG_ENTRIES.flatMap(productSection),
    "## Services",
    "",
    "Not counted towards the catalog size: a service is made to the customer's geometry.",
    "",
    table(
      ["Service", "Class", "Implemented", "Pricing model", "Pricing", "Manufacturing", "Lead time"],
      SERVICES.map((service) => [
        `${service.name} (${service.route})`,
        service.productClass,
        fact(service.implemented),
        fact(service.pricingModel),
        fact(service.pricing),
        fact(service.manufacturing),
        fact(service.leadTime),
      ]),
    ),
    "",
    "## Policies",
    "",
    "### Product classes",
    "",
    "- **STANDARD_CATALOG_PRODUCT** — a defined part at a fixed catalog price.",
    "- **CONFIGURABLE_PRODUCT** — a defined part whose price depends on customer choices.",
    "- **QUOTE_ONLY_PRODUCT** — no catalog price; requires `priceStatus: quote-only`, price 0, pricing model QUOTE_ONLY.",
    "- **CUSTOM_MANUFACTURING_SERVICE** — the customer's own geometry; a service, never a catalog product.",
    "- A product that is not launch-ready is not a class: it is the computed launch status of any class.",
    "",
    "### Pricing",
    "",
    "- **Fixed** prices become commercial only through a price approval record (amount in whole rupees, INR, effective date, reference, approver) whose amount equals the product price. The CMS refuses `priceStatus: approved` otherwise, and the storefront re-checks it on every read.",
    "- Output of the quote engine (`demo-2026-01`) is **PROVISIONAL** and is never promoted to an approved price because it produces a number.",
    "- A price approval not yet in effect authorises nothing.",
    "",
    "### Images and renders",
    "",
    "- Required visual per product: **REAL_PHOTO** or **APPROVED_RENDER**. Until one exists the product is **NO_IMAGE_YET**.",
    "- An image must be classified as `photo` or `render`; an unclassified image is refused, so placeholder media cannot satisfy the requirement.",
    "- A render must be produced from the product's own verified model, show the actual geometry and be labelled as a render. No render is presented as photography.",
    "- The image kind must match the approved requirement (a REAL_PHOTO requirement is not met by a render).",
    "",
    "### Product description standard",
    "",
    "1. **What it is** — plain, specific, no marketing superlatives.",
    "2. **Use case** — what it is intended for, matching the approved use case.",
    "3. **Technical information** — only verified facts: dimensions measured from the model, counts from the model or its generator.",
    "4. **Manufacturing information** — only approved capability; unapproved capability is not stated as fact.",
    "5. **Material** — only materials offered for the product.",
    "6. **Limitations** — every known limitation stated (for example, a non-involute tooth form).",
    "7. **Disclaimer** — no part is certified for safety-critical use, and none is implied to be. No tolerance, strength, temperature, certification, weight, lead time or guarantee is stated without approved data; validation rejects copy that does.",
    "",
    "### Capability status",
    "",
    ...CAPABILITY_STATES,
    "",
    `Now: available — ${statusList("technology", "AVAILABLE")}; ${statusList("material", "AVAILABLE")}; ${statusList("finish", "AVAILABLE")} finish. Coming soon — ${statusList("technology", "COMING_SOON")}; ${statusList("material", "COMING_SOON")}; ${statusList("finish", "COMING_SOON")} finishes. A product on a Coming Soon capability can be drafted in the admin and cannot be published or become launch-ready.`,
    "",
    "### Homepage featuring",
    "",
    "A product is featured only when all hold: approval status APPROVED, published, price APPROVED, approved media, manufacturing capability APPROVED, commercial decisions APPROVED, technically valid, and the featured flag set. `featured` cannot bypass launch readiness.",
    "",
  ];

  return out.join("\n");
}

export const GENERATED_DOCS: readonly { path: string; render: () => string }[] = [
  { path: "MANUFACTURING_CAPABILITY.md", render: renderManufacturingCapability },
  { path: "LAUNCH_CATALOG.md", render: renderLaunchCatalog },
];
