import type { ModelAsset } from "./types";

/**
 * Verified 3D model assets.
 *
 * Every figure below was measured by parsing the file — the STLs through the
 * application's own mesh parser and geometry analyser, the GLB from its glTF
 * accessors and node transforms — and `catalog.test.ts` measures them again on
 * every test run. Nothing here is transcribed from a description.
 *
 * All three are generated by `scripts/generate-models.mjs`, parametrically, so
 * the geometry is reproducible from source. STL records no unit; the generator
 * authors in millimetres, and the measured envelopes are consistent with that.
 *
 * Removed in the reset: `cable-bracket.stl`. It parses, but its only "hole" is a
 * 3.2 mm channel running along the inside of a 4 mm leg, leaving 0.4 mm walls
 * and no fixing hole through the part — it did not describe the product it was
 * attached to, and it is not a part worth selling as drawn.
 */
export const MODEL_ASSETS = {
  spurGear24t: {
    url: "/models/spur-gear-24t.stl",
    format: "stl",
    sizeBytes: 28_884,
    partCount: 1,
    envelopeMm: { x: 49.93, y: 49.93, z: 8 },
    source: "scripts/generate-models.mjs — gear({ teeth: 24, pitch: 22, depth: 3, boreRadius: 3, thickness: 8 })",
  },
  planetaryGearSet: {
    url: "/models/planetary-gear-set.glb",
    format: "glb",
    sizeBytes: 156_592,
    partCount: 6,
    envelopeMm: { x: 60, y: 23.5, z: 60 },
    source: "scripts/generate-models.mjs — planetaryCarrier()",
  },
  hexShaftSpacer: {
    url: "/models/hex-shaft-spacer.stl",
    format: "stl",
    sizeBytes: 6_084,
    partCount: 1,
    envelopeMm: { x: 19.05, y: 22, z: 34 },
    source: "scripts/generate-models.mjs — coupler({ across: 11, boreRadius: 4, height: 34 })",
  },
} as const satisfies Record<string, ModelAsset>;

export const VERIFIED_MODELS: readonly ModelAsset[] = Object.values(MODEL_ASSETS);
