/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    materials: Material;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Parts SADA 3D sells. Unpublish to withdraw; do not delete.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Stable identifier, e.g. "p-001". Carts, saved items and past orders refer to this. Never change it on a live product.
   */
  productId: string;
  /**
   * URL segment. Changing it breaks every existing link to this part.
   */
  slug: string;
  /**
   * One short technical line. Used by search; not shown on the card.
   */
  summary: string;
  /**
   * Two sentences at most. Engineering-plain.
   */
  description?: string | null;
  applications?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Whole rupees. Zero means the part is quoted from the customer's own geometry and cannot be added to a cart.
   */
  price: number;
  currency: 'INR';
  availability: 'in-stock' | 'made-to-order';
  /**
   * Small corner label, e.g. "New". Ration these.
   */
  badge?: string | null;
  /**
   * The leaf category this part is filed under. Ancestors are derived from the tree, not stored.
   */
  category: number | Category;
  /**
   * The top-level destination whose URL this part lives under. Must be a browse category.
   */
  browseCategory: number | Category;
  /**
   * The default material this part is made in.
   */
  material: number | Material;
  /**
   * Every material offered, including the default. One entry means the material is fixed and is shown as metadata rather than as a choice.
   */
  materials?: (number | Material)[] | null;
  technology: 'fdm' | 'sla' | 'sls';
  /**
   * Default colour facet value, e.g. black. Must be one of the colours the marketplace filters on.
   */
  color: string;
  /**
   * Every colour offered, including the default.
   */
  colors?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  qualityOptions?:
    | {
        value: string;
        label: string;
        /**
         * e.g. "0.16 MM".
         */
        layerHeight: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only rows that are actually known for this part. An empty table is better than an invented one.
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  materialNotes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Additional views. The gallery only appears when there is more than one image.
   */
  gallery?: (number | Media)[] | null;
  /**
   * A mesh the 3D viewer can render. Leave empty and the card falls back to the placeholder stage.
   */
  model?: {
    url?: string | null;
    format?: ('stl' | 'obj' | 'glb' | 'gltf') | null;
  };
  /**
   * Optional. The product page falls back to the name and the description when these are empty, which is what it does today.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The category tree the marketplace filters on.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Shown in filters and breadcrumbs, e.g. "Gears".
   */
  name: string;
  /**
   * Stable identifier used in URLs and by products. Lowercase, hyphenated. Changing it breaks existing links.
   */
  value: string;
  /**
   * Leave empty for a top-level category.
   */
  parent?: (number | null) | Category;
  /**
   * Appears in the shop category rail and gets its own /shop/[category] page.
   */
  isBrowse?: boolean | null;
  /**
   * Rail order. Lower first.
   */
  browseOrder?: number | null;
  /**
   * Optional. The category page falls back to its name and the site defaults when these are empty.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * How each manufacturing material is described to customers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: number;
  /**
   * Must match a material the manufacturing domain knows: pla, petg, abs, tpu or resin. Not free text — the quote engine narrows against these.
   */
  value: string;
  /**
   * Display name, e.g. "PETG".
   */
  name: string;
  /**
   * Chemistry or process, e.g. "Glycol-modified PET".
   */
  code?: string | null;
  /**
   * One or two sentences. Engineering-plain: what it is and what it is for.
   */
  description?: string | null;
  /**
   * Relative, 1 to 5. These drive the property scales on the homepage, not any engineering claim.
   */
  properties: {
    strength: number;
    flexibility: number;
    heat: number;
  };
  /**
   * What this material is typically used for.
   */
  applications?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How a finished part looks.
   */
  surface?: ('matte' | 'gloss' | 'machined' | 'soft' | 'translucent') | null;
  /**
   * Colours this material is stocked in, as swatches.
   */
  swatches?:
    | {
        /**
         * e.g. #FF6B00
         */
        hex: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional sample render.
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Public product imagery. Never customer files.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers. Describe the part, not the photo.
   */
  alt: string;
  /**
   * Attribution, where one is required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Content operators with access to this admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in version history and audit trails.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'materials';
        value: number | Material;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  productId?: T;
  slug?: T;
  summary?: T;
  description?: T;
  applications?:
    | T
    | {
        value?: T;
        id?: T;
      };
  price?: T;
  currency?: T;
  availability?: T;
  badge?: T;
  category?: T;
  browseCategory?: T;
  material?: T;
  materials?: T;
  technology?: T;
  color?: T;
  colors?:
    | T
    | {
        value?: T;
        id?: T;
      };
  qualityOptions?:
    | T
    | {
        value?: T;
        label?: T;
        layerHeight?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  materialNotes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  image?: T;
  gallery?: T;
  model?:
    | T
    | {
        url?: T;
        format?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  parent?: T;
  isBrowse?: T;
  browseOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  value?: T;
  name?: T;
  code?: T;
  description?: T;
  properties?:
    | T
    | {
        strength?: T;
        flexibility?: T;
        heat?: T;
      };
  applications?:
    | T
    | {
        value?: T;
        id?: T;
      };
  surface?: T;
  swatches?:
    | T
    | {
        hex?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Copy for the homepage sections. Layout is code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    subheadline?: string | null;
  };
  /**
   * Real catalog products. Names and prices come from the product, so they cannot disagree with the product page.
   */
  featuredProducts?: (number | Product)[] | null;
  /**
   * Figures SADA 3D can stand behind. An invented number here is a claim made to every visitor.
   */
  capabilityMetrics?:
    | {
        /**
         * e.g. "12" or "0.05 MM".
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  industries?:
    | {
        index: string;
        name: string;
        summary: string;
        /**
         * How much of the grid row this occupies. The only layout choice exposed here.
         */
        span?: ('wide' | 'narrow') | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
      };
  featuredProducts?: T;
  capabilityMetrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        index?: T;
        name?: T;
        summary?: T;
        span?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}